# Development database configuration
development:
  postgres:
    host: 'ttdata.postgres.database.azure.com'
    port: '5432'
    user: 'ttdata'
    password: 'VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5Fd0R4TWQ3M0tja0llWHpTNWNVNkxpQzIK'
    database: 'couchdb_new'
  
  couchdb:
    url: 'https://couchdb:4Ze7WOaVB3OoWYH13seSIdt9@tex-tracer.redledger.eu'

# Test configuration (if needed)
test:
  postgres:
    host: 'localhost'
    port: '5432'
    user: 'test'
    password: 'test'
    database: 'tt-spark-test'

# Default environment
environment: 'development'